#ifndef SOMNIA_AGENT_H
#define SOMNIA_AGENT_H

#include "common.h"
#include "value.h"
#include "table.h"

/**
 * Agent Cognitive Model
 * 
 * ID  = Unconscious (rules, drives, affects) → generates Proposals
 * EGO = Subconscious (policies, filters)    → selects Proposals
 * ACT = Conscious (action execution)        → executes Actions
 */

// ============================================================================
// DRIVES & AFFECTS
// ============================================================================

typedef struct {
    ObjString* name;
    double intensity;  // 0.0 to 1.0
} Drive;

typedef struct {
    ObjString* name;
    double valence;    // -1.0 to 1.0
} Affect;

typedef struct {
    ObjString* source;
    ObjString* target;
    double strength;   // 0.0 to 1.0
} Association;

// ============================================================================
// PROPOSAL (generated by ID)
// ============================================================================

typedef struct {
    ObjString* action;          // Action name
    Table args;                 // Arguments
    double weight;              // 0.0 to 1.0
    ObjString* ruleId;          // Which rule generated this
    int ruleLine;               // Line number
    ObjString* explanation;     // Optional explanation
} Proposal;

typedef struct {
    Proposal* proposals;
    int count;
    int capacity;
} ProposalArray;

void initProposalArray(ProposalArray* array);
void writeProposalArray(ProposalArray* array, Proposal proposal);
void freeProposalArray(ProposalArray* array);
void sortProposalsByWeight(ProposalArray* array);

// ============================================================================
// INTENT (external trigger)
// ============================================================================

typedef struct {
    ObjString* name;
    Table args;
} Intent;

// ============================================================================
// FACT (world state)
// ============================================================================

typedef struct {
    ObjString* key;
    Value value;
} Fact;

typedef struct {
    Fact* facts;
    int count;
    int capacity;
} FactArray;

void initFactArray(FactArray* array);
void writeFactArray(FactArray* array, Fact fact);
void freeFactArray(FactArray* array);
Value getFactValue(FactArray* array, const char* key);

// ============================================================================
// EXECUTION CONTEXT
// ============================================================================

typedef struct {
    Intent intent;              // Current intent
    FactArray facts;            // World state
    Drive* drives;              // Active drives
    int driveCount;
    Affect* affects;           // Current affects
    int affectCount;
    Association* associations; // Learned associations
    int associationCount;
    uint64_t seed;             // Random seed for determinism
    uint64_t timestamp;        // Current timestamp
} ExecutionContext;

void initExecutionContext(ExecutionContext* ctx);
void freeExecutionContext(ExecutionContext* ctx);

// ============================================================================
// ACTION RESULT
// ============================================================================

typedef enum {
    ACTION_SUCCESS,
    ACTION_ERROR_RETRYABLE,
    ACTION_ERROR_FATAL,
    ACTION_TIMEOUT,
    ACTION_CANCELLED
} ActionResultType;

typedef struct {
    ActionResultType type;
    Value result;
    ObjString* errorMessage;
    double durationMs;
} ActionResult;

// ============================================================================
// CYCLE RESULT
// ============================================================================

typedef struct {
    ProposalArray generatedProposals;   // From ID
    ProposalArray selectedProposals;    // After EGO
    ActionResult* results;              // From ACT
    int resultCount;
    double totalDurationMs;
    ObjString* traceId;
} CycleResult;

void initCycleResult(CycleResult* result);
void freeCycleResult(CycleResult* result);

#endif // SOMNIA_AGENT_H
