package somnia.core.model

import somnia.core.value.SomniaValue

/**
 * Proposal - A candidate action generated by ID.
 * Proposals are evaluated and selected by EGO.
 */
data class Proposal(
    val action: String,
    val args: Map<String, SomniaValue>,
    val weight: Double,
    val provenance: Provenance,
    val explanation: String? = null
) {
    init {
        require(weight in 0.0..1.0) { "Proposal weight must be between 0.0 and 1.0" }
    }
    
    /** Create a copy with adjusted weight */
    fun withWeight(newWeight: Double) = copy(weight = newWeight.coerceIn(0.0, 1.0))
    
    /** Create a copy with added explanation */
    fun withExplanation(text: String) = copy(explanation = text)
}

/**
 * Provenance - Tracks where a proposal came from.
 * Essential for debugging and explainability.
 */
data class Provenance(
    val ruleId: String,
    val ruleLine: Int,
    val matchedConditions: List<String>,
    val timestamp: Long = System.currentTimeMillis()
)

/**
 * SelectedProposal - A proposal that passed EGO filtering.
 * Includes selection metadata.
 */
data class SelectedProposal(
    val proposal: Proposal,
    val rank: Int,
    val selectionReason: String
)

/**
 * RejectedProposal - A proposal that was filtered by EGO.
 * Includes rejection reason for debugging.
 */
data class RejectedProposal(
    val proposal: Proposal,
    val reason: RejectionReason,
    val policyId: String?
)

/**
 * Reasons why a proposal might be rejected.
 */
enum class RejectionReason {
    FORBIDDEN,          // Matched a forbid rule
    BUDGET_EXCEEDED,    // Rate limit hit
    LOW_WEIGHT,         // Below threshold
    NOT_SELECTED        // Didn't make top N
}

/**
 * WeightModifiers - Factors that influence proposal weight.
 */
data class WeightModifiers(
    val base: Double,
    val driveModifier: Double = 1.0,
    val affectModifier: Double = 1.0,
    val recencyBonus: Double = 0.0,
    val noveltyBonus: Double = 0.0
) {
    fun compute(): Double = (base * driveModifier * affectModifier + recencyBonus + noveltyBonus)
        .coerceIn(0.0, 1.0)
}
